version: "3.7"
services:
  db:
    build: development/db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - DB_APP_NAME=loopsnelheid-db
      - DB_APP_USER=loopsnelheid-db
      - DB_APP_PASS=loopsnelheid-db
    volumes:
      - "./data:/var/data/db"
    networks:
      - shared_network
  mailcatcher:
    image: schickling/mailcatcher
    container_name: loopsnelheid-mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - shared_network
  api:
    image: ghcr.io/team-dom-toren/loopsnelheid-app-api/api:v0.0.3
    container_name: loopsnelheid-api
    ports:
      - "8080:8080"
    networks:
      - shared_network
  nginx:
    image: nginx:latest
    container_name: loopsnelheid-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - shared_network
networks:
  shared_network: