version: "3.7"
services:
  db:
    build: development/db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - DB_APP_NAME=loopsnelheid-db
      - DB_APP_USER=loopsnelheid-db
      - DB_APP_PASS=loopsnelheid-db
    volumes:
      - "./data:/var/data/db"
    networks:
      - shared_network
  mailcatcher:
    image: schickling/mailcatcher
    container_name: loopsnelheid-mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"